services:
  host-primary:
    image: minimal-web-db:latest
    container_name: minimal-web-db-host-primary
    restart: always
    ports:
      - 9090:9990
      - 7070:8080
    volumes: 
      - wildfly_controller:/etc/wildfly

  host-slave01:
    image: minimal-web-db:latest
    container_name: minimal-web-db-host-slave01
    restart: always
    ports:
      - 9091:9990
      - 7071:8080
    volumes:
      - wildfly_slave01:/etc/wildfly
volumes:
  wildfly_controller:
  wildfly_slave01: