services:
  load-balance:
    image: haproxy:trixie
    hostname: SVLLAB0001
    container_name: load-balance
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8084:8084
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/certs/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem
    depends_on:
      - proxy-reverse-host-master
      - proxy-reverse-host-slave01
      - host-master
      - host-slave01

    networks:
      - web-infrastructure-lab_default

  proxy-reverse-host-master:
    image: nginx:mainline-alpine3.23-perl
    hostname: SVLLAB0002
    container_name: proxy-master
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - web-infrastructure-lab_default
    depends_on:
      - host-master
    
  proxy-reverse-host-slave01:
    image: nginx:mainline-alpine3.23-perl
    hostname: SVLLAB0003
    container_name: proxy-slave
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - web-infrastructure-lab_default
    depends_on:
      - host-slave01

  host-master:
    image: demo:latest
    hostname: SVLLAB0004
    container_name: host-master
    restart: always
    ports:
      - 5050:8080
      - 3030:9990
    environment:
      HOST_CONFIG: host.xml
      MGMT_USER: administrator
      MGMT_PASSWD: admin
    volumes:
      - wildfly_controller:/etc/wildfly
    networks:
      - web-infrastructure-lab_default

  host-slave01:
    image: demo:latest
    container_name: host-slave01
    hostname: SVLLAB0005
    restart: always
    depends_on:
      - host-master
    environment:
      HOST_CONFIG: host-slave.xml
      DOMAIN_CONTROLLER: host-master
      MGMT_USER: administrator
      MGMT_PASSWD: admin
    volumes:
      - wildfly_slave01:/etc/wildfly
    networks:
      - web-infrastructure-lab_default

volumes:
  wildfly_controller:
  wildfly_slave01:

networks:
  web-infrastructure-lab_default:
    external: true
