worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 100;
}

http {
    server{
        listen 80;
        server_name _;

        location / {
            root /etc/nginx/sites-available;
        }
    }
}